### ISSUE TITLE
Search UI improvements 

### ISSUE THREAD

**Issue by jmsaulnier** [elastos/Elastos.Trinity.DApps.DAppsStore#2]
## Current Behavior
1. When searching "Test", the result is "dApp Store" - is the search uses tags? or by name only?
2. Result gives the same dApp in 3 different categories (New Release, Popular, Finance)
3. When no result, the result is empty
4. When the user scrolls down, search - the first result has a padding issue
![Screen Shot 2020-01-01 at 8 51 24 PM](https://user-images.githubusercontent.com/145750/71652187-7ecacf00-2cd8-11ea-954b-b484abb379fd.png)

## Expected Behavior
1. Remove "dApp Store" when searching "Test"
2. Add only one category for the result 
3. When no result, add a message
4. User see the first item

@BenjaminPiette

**Comment by chadracelis** [comment]
Displayed 'no results' for 0 search results. thankyou
